### ISSUE TITLE
Can we use a different table other than kv_storage?

### ISSUE THREAD

**Issue by centralcybersecurity** [SoftinkLab/laravel-keyvalue-storage#2]
Hi,
I already have a key:value table and I want to use that instead of creating a new kv_storage table.
Where do I change the table name and use this package with the existing table?
Thanks

**Comment by PasanBhanu** [comment]
Hi, Thanks for the comment. I'll add this feature. If you already added, please create a pull request.
Thanks

**Comment by PasanBhanu** [comment]
Fixed. Will release in 1.8
